# overrides for local development, not used in CI
version: '3'
services:
  pandoc-lambda:
    volumes:
      - ./docker/pandoc-lambda/function/:/function
    build:
      context: docker/pandoc-lambda
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
